### PR TITLE
feat: Add parity

### PR DESCRIPTION
**Pull request by mikhaelsantos**
Switch Ganache to parity POA
* Added Parity POA now called open-ethereum
* Added Smart Contract init (Re-used code from streamr-ganache) addresses at:https://github.com/streamr-dev/smart-contracts-init

### CODE REVIEW

**Comment by isentropy** [comment]
Appears to be working. I checked out the blockchain in blockscout and all the init transactions are there. Maybe try to get it working with 1 node. I suppose fewer moving parts is better.

**Comment by isentropy** [comment]
Which addresses are given ETH in this chain? I see that differs from ganache

**Comment by isentropy** [comment]
The allocation should match ganache with mnenonic "testrpc":

Available Accounts
==================
(0) 0xa3d1F77ACfF0060F7213D7BF3c7fEC78df847De1 (100 ETH)
(1) 0x4178baBE9E5148c6D5fd431cD72884B07Ad855a0 (100 ETH)
(2) 0xdC353aA3d81fC3d67Eb49F443df258029B01D8aB (100 ETH)
(3) 0x7986b71C27B6eAAB3120a984F26511B2dcfe3Fb4 (100 ETH)
(4) 0xa6743286b55F36AFA5F4e7e35B6a80039C452dBD (100 ETH)
(5) 0x7B556228B0D887CfC8d895cCe27CbC79d3e55b3C (100 ETH)
(6) 0x795063367EbFEB994445d810b94461274E4f109A (100 ETH)
(7) 0xcA9b39e7A7063cDb845483426D4f12F1f4A44A19 (100 ETH)
(8) 0x505D48552Ac17FfD0845FFA3783C2799fd4aaD78 (100 ETH)
(9) 0x65416CBeF822290d9A2FC319Eb6c7f6D9Cd4a541 (100 ETH)

Private Keys
==================
(0) 0x5e98cce00cff5dea6b454889f359a4ec06b9fa6b88e9d69b86de8e1c81887da0
(1) 0xe5af7834455b7239881b85be89d905d6881dcb4751063897f12be1b0dd546bdb
(2) 0x4059de411f15511a85ce332e7a428f36492ab4e87c7830099dadbf130f1896ae
(3) 0x633a182fb8975f22aaad41e9008cb49a432e9fdfef37f151e9e7c54e96258ef9
(4) 0x957a8212980a9a39bf7c03dcbeea3c722d66f2b359c669feceb0e3ba8209a297
(5) 0xfe1d528b7e204a5bdfb7668a1ed3adfee45b4b96960a175c9ef0ad16dd58d728
(6) 0xd7609ae3a29375768fac8bc0f8c2f6ac81c5f2ffca2b981e6cf15460f01efe14
(7) 0xb1abdb742d3924a45b0a54f780f0f21b9d9283b231a0a0b35ce5e455fa5375e7
(8) 0x2cd9855d17e01ce041953829398af7e48b24ece04ff9d0e183414de54dc52285
(9) 0x2c326a4c139eced39709b235fffa1fde7c252f3f7b505103f7b251586c35d543

**Comment by isentropy** [comment]
deploys should be done with first key 0xa3d1F77ACfF0060F7213D7BF3c7fEC78df847De1. Then contract addresses will match ganache

**Comment by isentropy** [comment]
you setup allocation in parity in the genesis.json file

**Comment by mikhaelsantos** [comment]
Can you elaborate on this @isentropy :
`you setup allocation in parity in the genesis.json file`

**Comment by isentropy** [comment]
the JS client lib test failure with parity was a timing issue with parity's 1m block time. I will add wait() to JS to fix test. Parity looks fine otherwise.

**Pull request merged**
