### PR TITLE
Unify naming of bridge components

### PR DESCRIPTION
**Pull request by hpihkala**
Just a cleanup PR, attempting to unify and clarify the naming of the new containers:

- Follow convention: prefix all containers with `streamr-dev-`
- Follow convention: use `-` instead of `_` as separator
- Prefix all containers belonging to the bridge with `streamr-dev-bridge-`
- Prefix all oracle processes with `streamr-dev-bridge-oracle-`
- Resolve `hostname` conflict between `redis` and `bridge-redis`

Could you check that everything still works?

- Specify Docker compose file version 3.7
- Specify names for docker volumes

### CODE REVIEW

**Comment by kare** [comment]
@hpihkala As this PR requires a `factory-reset` from developers. Could we fix the naming of docker-compose components with the prefix `streamr-docker-dev` -> `streamr-dev`?

**Comment by hpihkala** [comment]
> @hpihkala As this PR requires a `factory-reset` from developers. Could we fix the naming of docker-compose components with the prefix `streamr-docker-dev` -> `streamr-dev`?

@kare Where do you see `streamr-docker-dev` prefix remaining?

(Side note: I guess just `streamr` prefix would be enough really)

**Comment by kare** [comment]
All networks and volumes are unnamed. +1 for streamr instead of streamr-dev
```
Creating network "streamr-docker-dev_default" with the default driver
Creating network "streamr-docker-dev_net_rabbit_bridge_collected" with driver "bridge"
Creating network "streamr-docker-dev_net_rabbit_bridge_senderforeign" with driver "bridge"
Creating network "streamr-docker-dev_net_rabbit_bridge_affirmation" with driver "bridge"
Creating network "streamr-docker-dev_net_rabbit_bridge_request" with driver "bridge"
Creating network "streamr-docker-dev_net_rabbit_bridge_senderhome" with driver "bridge"
Creating network "streamr-docker-dev_net_db_bridge_collected" with driver "bridge"
Creating network "streamr-docker-dev_net_db_bridge_senderforeign" with driver "bridge"
Creating network "streamr-docker-dev_net_db_bridge_affirmation" with driver "bridge"
Creating network "streamr-docker-dev_net_db_bridge_senderhome" with driver "bridge"
Creating network "streamr-docker-dev_net_db_bridge_request" with driver "bridge"
Creating volume "streamr-docker-dev_data" with default driver
Creating volume "streamr-docker-dev_mysql_init_scripts" with default driver
Creating volume "streamr-docker-dev_cassandra_init_scripts" with default driver
```

**Comment by kare** [comment]
@hpihkala Seems that Travis CI doesn't support recent Docker version.

**Comment by kare** [comment]
Travis CI has Ubuntu 20.04 image with Docker 19.03.8.
GitHub has Ubuntu 20.04 image with Docker 19.03.13.
My local Docker is 19.03.13 and volume names work locally.
I've run into problems with Travis CI's old Docker version before.

**Comment by hpihkala** [comment]
@kare does this mean that Travis CI of all other repos that use `streamr-docker-dev` will break, unless they upgrade the config in that repo to use Ubuntu 20?

**Comment by kare** [comment]
@hpihkala I'm afraid that I'll have to revert volume naming commit. I'll try it again later and after that I'll check if network's can be named.

**Review by timoxley — APPROVED** [review]
lgtm

**Comment by kare** [comment]
This PR breaks some of the commands and needs to be reworked:
- https://github.com/streamr-dev/streamr-docker-dev/pull/117

There is a miss-match with the prefix and docker-compose -p arg.

**Pull request closed without merging**
