### PR TITLE
added ens-sync-fastchain container entry

### PR DESCRIPTION
**Pull request by samt1803**
main PR is https://github.com/streamr-dev/network-contracts/pull/615

ticket for that is https://linear.app/streamr/issue/ETH-568/add-ens-stream-creation-support-to-fast-chain

### CODE REVIEW

**Review by jtakalai — APPROVED** [review]
should it have a health check? I wrote a quick attempt at something like that, though really it's kind of hard to know if it REALLY is healthy before there is traffic -___- see #617

**Review by samigabor — APPROVED** [review]

**Review by harbu — COMMENTED** [review]
Is this ETH-568?

We should add some kind of health check at least. Adding a few comments to what @jtakalai is working on.

**Comment by samt1803** [comment]
> 

Ah I didn't see that ticket. It is that, together with [#615](https://github.com/streamr-dev/network-contracts/pull/615), that needs this to be merged to get green in CI and now [#617](https://github.com/streamr-dev/network-contracts/pull/615)

**Comment by jtakalai** [comment]
> Could we add that here?
I think since it has its own PR, we could just leave it out from here. Let's get this one merged.

**Comment by harbu** [comment]
Having the health check here is kind of important if we want to re-enable the skipped tests in client related to this feature (mainly https://github.com/streamr-dev/network/blob/streamr-1.0/packages/client/test/end-to-end/StreamRegistry.test.ts#L116). Unless we have another way to verify that the service is running before starting the test run?

**Review by jtakalai — APPROVED** [review]

**Pull request merged**
